### PR TITLE
DBRIDER-358 = add scripting support in `@ExpectedDataSet`

### PR DESCRIPTION
**Pull request by coiouhkc**
Implementing suggestion from https://github.com/database-rider/database-rider/issues/358

### CODE REVIEW

**Comment by rmpestano** [comment]
Hey @coiouhkc, looks really nice!

I'm not sure you're done, if so I can open a PR and contribute to your branch. Following is what I'd like to have as part of this PR:

* Extract [each kind of assertion ](https://github.com/database-rider/database-rider/blob/ba7b8a9d5c821918481714160ef53861e1fa76f4/rider-core/src/main/java/com/github/database/rider/core/assertion/DataSetAssert.java#L82-L120)(regex, script and "normal one") into separated classes
* Unit test `ScriptEngineManagerWrapper`
* Add more script assertion examples

Thank you!

**Comment by coiouhkc** [comment]
> I'm not sure you're done, if so I can open a PR and contribute to your branch.

Hi @rmpestano, i'm done for today, hope to come back to it later some evening this week or on the weekend. I've sent you an invitation to work directly in my branch, just in case.. ;)

**Comment by coiouhkc** [comment]
Hm, it looks like i've opened the PR too early, the test fails.. :( Sorry about that.

**Comment by rmpestano** [comment]
> Hm, it looks like i've opened the PR too early, the test fails.. :( Sorry about that.
> For whatever reason the comparison is being run twice, second time is failing - any idea?

No worries, take your time, I'll try to help if I find some tie. Thanks again!

**Comment by coiouhkc** [comment]
Hi @rmpestano, why do you ignore `rowNum` and `columnName` in https://github.com/database-rider/database-rider/blob/5c0aa5f3e0558c7bb612474d1731de0496519540/rider-core/src/main/java/com/github/database/rider/core/assertion/DataSetAssert.java#L103 ? 

It causes all the checks to be executed in O(n^2) instead of O(n), as per stacktrace 
```
at com.github.database.rider.core.assertion.DataSetAssert.compareData(DataSetAssert.java:111)
at com.github.database.rider.core.assertion.DataSetAssert.compareData(DataSetAssert.java:129)
at org.dbunit.assertion.DbUnitAssertBase.compareData(DbUnitAssertBase.java:561)
at org.dbunit.assertion.DbUnitAssertBase.assertWithValueComparer(DbUnitAssertBase.java:439)
```

**Comment by rmpestano** [comment]
> Hi @rmpestano, why do you ignore `rowNum` and `columnName` in

Hi, if I'm not wrong it was introduced in newer dbunit versions. If we can use that and also be compatible with previous versions of dbunit then I'd go for it.

> It causes all the checks to be executed in O(n^2) instead of O(n), as per stacktrace

While it's great to have linear performance instead of exponential we also have small datasets, you hardly will have datasets with hundreds of rows, usually, you have dozens of rows in each dataset.

**Comment by rmpestano** [comment]
> For whatever reason the comparison is being run twice, second time is failing - any idea?

I've sent a PR to your branch regarding to that and seems the test is now passing. We need to ad more examples, If I find some time I'll try to help

**Comment by rmpestano** [comment]
@coiouhkc, I've added tests and refactored the script assert a bit, can you merge into your branch?

**Comment by coiouhkc** [comment]
Hi @rmpestano , thanks for taking this PR further.
I don't quite like the workaround, but you certainly have more insights and I really appreciate your support.

**Comment by rmpestano** [comment]
Hi,

> I don't quite like the workaround, but you certainly have more insights and I really appreciate your support.

Me neither but we'll be able to get ride-off it once we use dbunit value comparers #113 (each kind of assertion in expected dataset will become a comparer). We hopefully will be able to remove our `DataSetAssert` implementation which is basically copied from dbunit and changed to rider needs.   

For that we need to require dbunit 2.6 or greater which is not a big issue as it's a test lib, maybe on next release.

Thank you for all the help!

**Pull request merged**
