### PR TITLE
Implement filter of actual table by values from expected table

### PR DESCRIPTION
**Pull request by iceberk**

### CODE REVIEW

**Comment by iceberk** [comment]
Yes, actually CONTAINS covers more narrow case than this implementation. My only concern is that it is slower than CONTAINS because it has to walk over every row and column of actual dataset. 
But DB tests were never fast, so I think it should be fine 😃

**Comment by iceberk** [comment]
I'll remove old implementation and replace it with this one.

**Comment by rmpestano** [comment]
> I'll remove old implementation and replace it with this one.

great!

**Comment by iceberk** [comment]
Removed CONTAINS_COLUMNS from enum, added null check for regex case and replaced comparison of values with org.dbunit.dataset.datatype.DataType#compare call (it should handle types conversion if needed).

**Comment by rmpestano** [comment]
Awesome, thank you very much @iceberk!

**Pull request merged**
