### PR TITLE
#37  Support for Case INsensitive YML dataset

### PR DESCRIPTION
**Pull request by jenskreidler**
Added database-rider configuration property "caseInsensitiveStrategy" pointing to Orthography enum constant (defaults to UPPERCASE, added in default/dbunit.yml). Strategy describes database identifiers used internally, if and only if caseSensitiveTableNames is set to false (i.e. database-rider runs in case-insensitive identifiers mode). Developers may configure @DBUnit on class oder method level in their test case.

### CODE REVIEW

**Comment by jenskreidler** [comment]
Sorry, did not check in a test source.

**Comment by jenskreidler** [comment]
We should add s.th. in RiderDataSource line 82: DatabaseConfig.findByShortName(p.getKey()).
Here we enter dbunit-api, leading to an undesired log output: 

"The property ending with 'caseInsensitiveStrategy' was not found. Please notify a dbunit developer to add the property to the class org.dbunit.database.DatabaseConfig"

It's up to the fact that "caseInsensitiveStrategy" is not a dbunit related property. Shall we separate this in any appropriate way we'll discuss later?

**Comment by rmpestano** [comment]
Oww this is really great, thank you very much @jenskreidler!

Now about: 

> "The property ending with 'caseInsensitiveStrategy' was not found. Please notify a dbunit developer to add the property to the class org.dbunit.database.DatabaseConfig"

Another approach is not add this as a [dbunit property here](https://github.com/jenskreidler/database-rider/blob/ee75a5d0fed206041799e67c28bf6eae2b38ff48/rider-core/src/main/java/com/github/database/rider/core/configuration/DBUnitConfig.java#L51) and add it as "general" one like cacheTableNames and leakHunter. Or keep as it is and not add it in RiderDataSource line 82.

What do you think?

**Comment by jenskreidler** [comment]
I'd suggest and already appended your first solution. So we separate dbunit properties in the properties-map and don't pollute semantics by invoking "DBUnitConfig#addDbunitProperty(...)" for the non-dbunit property "caseInsensitiveStrategy".

**Pull request merged**
