### PR TITLE
ExpectedDataSet can not find table when yaml format is using

### PR DESCRIPTION
**Pull request by artemy-osipov**
corresponding issue  #21

### CODE REVIEW

**Comment by artemy-osipov** [comment]
@rmpestano, could you review pull request?

**Comment by rmpestano** [comment]
Hi @artemy-osipov, I will review ASAP (hope till tomorow). Thank you so far!

**Comment by artemy-osipov** [comment]
Hello @rmpestano. DBUnit cannot find `user` table because HSQLDB transform all unquoted names to uppercase
> A unquoted identifier (name) starts with a letter and is followed by any number of ASCII letters or digits. When an SQL statement is issued, any lowercase characters in unquoted identifiers are converted to uppercase. Because of this, unquoted names are in fact ALL UPPERCASE when used in SQL statements. An important implication of this is the for accessing columns names via JDBC DatabaseMetaData: the internal form, which is the ALL UPPERCASE must be used if the column name was not quoted in the CREATE TABLE statement.

I added fixed test for lowercase tables in the pull request

**Comment by rmpestano** [comment]
Beautiful! thank you again @artemy-osipov

**Pull request merged**
