### PR TITLE
added test for identity columns population in MS SQL Server

### PR DESCRIPTION
**Pull request by xpinjection**

### CODE REVIEW

**Comment by xpinjection** [comment]
It would be great to release new version. Then we could switch from local snapshot. :)

**Comment by rmpestano** [comment]
v1.5.3 is already on [maven central](https://search.maven.org/search?q=database-rider), thank you very much for your contributions. Also see release [notes here](https://github.com/database-rider/database-rider/releases/tag/1.5.3).

**Comment by xpinjection** [comment]
I have several additional ideas for contribution. One of them is XSD generation from JDBC metadata like it was implemented in Unitils. Hope to have time for that soon.

**Comment by rmpestano** [comment]
Note that dbrider already generates [datasets from a database](https://github.com/database-rider/dbunit-addon/#usage) or can [export datasets](https://github.com/database-rider/database-rider#export-datasets) after a test.

Don't know if your ideas go into that direction but I'm looking forward to it!

**Comment by xpinjection** [comment]
I prefer XML for datasets and generated XSD could provide autocomplete and validation options.

**Pull request merged**
