### PR TITLE
Fix foreign key constraint statements for H2

### LINKED ISSUE #375: disableConstraints=true for H2 executes non-H2 SQL Statement
I am using h2 version 2.0.202 and DBRider 1.32.0.

When I use `@DataSet(value = "datasets/mydataset.yml", disableConstraints = true)`, this line will run a `SET foreign_key_checks=0` statement, which is not supported by H2.

Instead, the command should be `SET REFERENTIAL_INTEGRITY FALSE` per documentation: https://www.h2database.com/html/commands.html#set_referential_integrity

So currently, I cannot use DataSets which would violate foreign key constraints.

### PR DESCRIPTION
**Pull request by bergerst**
Fixes #375

### CODE REVIEW

**Comment by rmpestano** [comment]
Look like the H2 upgrate broken flyway example, does it work locally for you @bergerst? (I didn't try on my machine)
 
Screenshot 2022-01-19 at 09 41 16

**Comment by bergerst** [comment]
The jOOQ example project is so outdated that it contains a buggy Flyway version. I tried updating, but then a chain of errors happens, including:

1. jOOQ doesn't find a `schema_version` table anymore because it now has a different name
2. jOOQ doesn't find any tables until you update the jOOQ plugin
3. The test class cannot be compiled anymore because the Flyway classes were completely changed

I decided to just revert that project to the old H2 version.

**Comment by rmpestano** [comment]
> I decided to just revert that project to the old H2 version.

That's fine, thanks!

**Comment by rmpestano** [comment]
I still see some issues in tests, I can have a look tomorrow if you don't have time:
Screenshot 2022-01-19 at 13 25 08

**Comment by bergerst** [comment]
> I still see some issues in tests, I can have a look tomorrow if you don't have time: Screenshot 2022-01-19 at 13 25 08

Looks like the tested class now suddenly sees the `INFORMATION_SCHEMA` tables, which didn't happen with the old h2 database.

I'm not sure how to deal with this as I don't know much about DBRider's source code. Either the tests need to be adjusted so the additionally detected tables are ignored or they have to be excluded from DBRider's view.

**Comment by rmpestano** [comment]
Hey @bergerst, sorry for the late reply,
 
> I'm not sure how to deal with this as I don't know much about DBRider's source code. Either the tests need to be adjusted so the additionally detected tables are ignored or they have to be excluded from DBRider's view.

Yea we'll have to adjust the tests, for DBRider it's important that it can find the tables declared in the dataset. I'll adjust the test to just assert tables in persistence.xml and push it to your branch.

Thanks!

**Pull request merged**
