### PR TITLE
Add orderBy option to @ExpectedDataSet

### PR DESCRIPTION
**Pull request by arhohuttunen**
When using ignoreOrder=true with @ExpectedDataSet Database Rider will take the columns from the expected dataset and use those to sort the actual and expected dataset rows before comparison.

### CODE REVIEW

**Comment by arhohuttunen** [comment]
After some reconsideration I'm thinking it would be better to provide a list of columns to sort by with a orderBy option. This is also the same that Arquillian persistence extension does. What do you think?

**Comment by rmpestano** [comment]
Hi @arhohuttunen,

Yes I think it's good idea to support multiple columns.

Thank you so far for the contribution!

**Comment by TopalSergey** [comment]
Hi @arhohuttunen,
Expected data sets supports regex in their columns with 'regex:' prefix. 
Is using orderBy and regex in same columns is mutually exclusive in your implementation? I think it will be good to throw an exception in this case (or implement one-to-many comparison 😊)

**Comment by arhohuttunen** [comment]
Hey @TopalSergey,

I wrote a test case for this and it fails indeed because the regex part changes the way the rows are sorted. The solution is so simple that the easiest thing to do in this case would be to throw an exception.

**Comment by rmpestano** [comment]
Hi again @arhohuttunen,

one small thing we need to fix is that [this test](https://github.com/database-rider/database-rider/pull/107/files#diff-c0e88a83ceca7caa5436b28e346178d6R116)  is not passing when we run it alone. The error is:

```
Caused by: org.hsqldb.HsqlException: integrity constraint violation: unique constraint or index violation; SYS_PK_10093 table: USER
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.Constraint.getException(Unknown Source)
``` 

This in mainly because the ids of the two users from [users.yml dataset ](https://github.com/database-rider/database-rider/pull/107/files#diff-c0e88a83ceca7caa5436b28e346178d6R114) are conflicting with the ID of user we're inserting inside the test. This conflict happens because hibernate allocated the sequence numbers when the entity manager was created (before users from dataset got inserted into the database).

To fix that I see two options:

1 - Use another **with negative ids** dataset to seed the database.
2 - use no dataset at all and insert all users inside the test:
```
    @Test
    @DataSet("yml/empty.yml")
    @ExpectedDataSet(value = "yml/expectedUsersIgnoreOrder.yml", orderBy = "NAME")
    public void shouldMatchExpectedDataSetIgnoringRowOrder() {
        User u1 = new User();
        u1.setName("@arhohuttunen");
        User u2 = new User();
        u2.setName("@realpestano");
        User u3 = new User();
        u3.setName("@dbunit");
        tx().begin();
        em().persist(u1);
        em().persist(u2);
        em().persist(u3);
        tx().commit();
    }
```

**Comment by rmpestano** [comment]
Thank you very much! 1.5.0 release should happen over this weekend.

**Pull request merged**
