### PR TITLE
Basic support of MS SQL Server

### PR DESCRIPTION
**Pull request by xpinjection**
Could you take a look at the draft version of MS SQL Server support and point me out what tests do you expect in addition to basic TestContainer test and concrete test with identity columns?

### CODE REVIEW

**Comment by rmpestano** [comment]
Hi @xpinjection, it looks really great!

> and point me out what tests do you expect in addition to basic TestContainer test and concrete test with identity columns?

I think these two tests would be enough but if you want to go a step further I would like to see l [disable constraints](https://github.com/database-rider/database-rider/blob/dfc54954f0ac8cf47c33efacf6e6078322a7b611/rider-core/src/test/java/com/github/database/rider/core/DatabaseRiderIt.java#L37) and [leak hunter](https://github.com/database-rider/database-rider/blob/master/rider-core/src/test/java/com/github/database/rider/core/LeakHunterIt.java) tests because they use database specific operations. Both tests can be on the same test class to avoid starting the test containers multiple times.

Thank you very much for your contribution so far, much appreciated!

**Comment by xpinjection** [comment]
It was my plan actually, but I didn't find such tests for other databases. :)

**Comment by rmpestano** [comment]
Yea they're missing indeed, that's why the "one step further" ;)

Also note that those feature are there for a long time so it is "likely" they are working on most databases as we don't see any related issues (or they are not beeing used at all).

**Comment by xpinjection** [comment]
Thanks for quick response! I will try to find time on this week for mentioned tests and add them to pull request.

**Comment by rmpestano** [comment]
Hi again @xpinjection,

I've added tests for leak hunter and disable constraints in PostgreSQL, [see here](https://github.com/database-rider/database-rider/commit/ee6563786ba59962166f754ee72c4882f53ab9db#diff-0addd03f5e604533218937bd3115caf2). It lead into an improvement into disable constraints feature for postgre, see #122.   

You may have to merge your branch into master before we merge this PR.

**Comment by xpinjection** [comment]
Great! I’m happy that our discussion already caused improvements in very useful library. Hope to have some time tomorrow to finish work on my pull request.

**Comment by rmpestano** [comment]
Hi @xpinjection,

you need any help here? looking at the PR travis build it looks like it is failing because of too much log output:

`The job exceeded the maximum log length, and has been terminated.`

Complete log [here](https://api.travis-ci.org/v3/job/518405961/log.txt) .

We may have to disable JPA logs in tests where possible, [see here](https://github.com/database-rider/database-rider/blob/1127c54b87aa84c9e938df4f444988a683fc0d35/rider-core/src/test/resources/META-INF/persistence.xml#L167) and [here](https://github.com/database-rider/database-rider/blob/1127c54b87aa84c9e938df4f444988a683fc0d35/rider-core/src/test/resources/logging.properties#L6).

**Comment by xpinjection** [comment]
@rmpestano thanks for your support! We are now testing implementation on different real world cases and hope to finish soon.

**Comment by rmpestano** [comment]
That's great! no hurry, just let me know if have any problems.

**Comment by xpinjection** [comment]
@rmpestano could you explain the idea behind caching of schemaName from JDBC metadata in DataSetExecutorImpl when getTableNames is invoked?

**Comment by rmpestano** [comment]
Hi, no I can't explain it ;) please remove this instance variable, less side effects/less suprises

**Comment by xpinjection** [comment]
@rmpestano could you review this pull request? it seems main features works for MS SQL Server according to our local testing.

**Comment by rmpestano** [comment]
It looks awesome, thank you very much for your time and contribution @xpinjection!!!

**Comment by xpinjection** [comment]
Hope it was just the first contribution. ;)

**Pull request merged**
