### PR TITLE
InsertIdentity operation for MS Sql server support

### PR DESCRIPTION
**Pull request by mrozk**

### CODE REVIEW

**Comment by rmpestano** [comment]
Hi @mrozk, first of all, thank you very much for your contribution!

Can you add a integration test which uses this new feature? I think we can have a MS SQL test similar to [Postgresql test](https://github.com/database-rider/database-rider/blob/dfc54954f0ac8cf47c33efacf6e6078322a7b611/rider-core/src/test/java/com/github/database/rider/core/PostgreSQLDatabaseIt.java#L19). Look here for a MS SQL Test Containers example: https://www.testcontainers.org/modules/databases/mssqlserver/

If you struggle with testcontainers just come back here and I'll try to help.

**Comment by xpinjection** [comment]
Hi @rmpestano! We would like to prepare pull request with full support of MS SQL confirmed with tests. Could you mention initial reasons why MS SQL was not included in DBType enum and all key features?

**Comment by rmpestano** [comment]
Hi @xpinjection, 

"Could you mention initial reasons why MS SQL was not included in DBType enum and all key features?" Basically because anyone involved on dbrider development had experience with MS SQL.

The contribution will be very much appreciated, thank you!

**Comment by xpinjection** [comment]
Great! Then we will try to implement all aspects and create pull request. Thanks for quick response!

**Comment by rmpestano** [comment]
Closing this as #121 is almost done. Anyway thank you very much for initial contribution @mrozk and feel free to give any feedback on #121!

**Pull request closed without merging**
