### PR TITLE
DBRIDER-505 = respect catalog/schema differentiation from JDBC

### PR DESCRIPTION
**Pull request by coiouhkc**
Suggested fix for #505

### CODE REVIEW

**Comment by coiouhkc** [comment]
@rmpestano - could you please trigger the outstanding checks?

**Comment by rmpestano** [comment]
> @rmpestano - could you please trigger the outstanding checks?

Hey @coiouhkc, I really don't know why those 2 checks are pending, they're related to old jobs we had, your PR is green  
Screenshot_20221027-140204

**Comment by rmpestano** [comment]
Thank you very much for the contribution!

**Comment by coiouhkc** [comment]
Thank you!
When do you plan to release the new version on Maven Central?

**Comment by rmpestano** [comment]
It will be released tomorrow 😉

**Pull request merged**
