### PR TITLE
Fix YamlDataSet table order

### PR DESCRIPTION
**Pull request by MetallFoX**
tables storage implementation changed from HashMap to LinkedHashMap to preserve order that yaml datasource file provides.

Fixes: #255

### CODE REVIEW

**Comment by rmpestano** [comment]
Hi @MetallFoX, thank you for the contribution.

I see there's one test failing: 

```
[ERROR] Failures: 
[ERROR]   DataSetExecutorImplTest.shouldLoadDatasetsFromURL:94 expected:<[TWEET]> but was:<[USER]>
[INFO] 
[ERROR] Tests run: 420, Failures: 1, Errors: 0, Skipped: 1
``` 

Can you have a look or it is passing locally?

**Comment by rmpestano** [comment]
Ok, just checked and I think you can just adjust to the [assertions here](https://github.com/MetallFoX/database-rider/blob/6836b8451ec1b3053184c0ffdf0239b06850d935/rider-core/src/test/java/com/github/database/rider/core/dataset/DataSetExecutorImplTest.java#L91-L96) to have the same order tables are [declared here](https://github.com/MetallFoX/database-rider/blob/6836b8451ec1b3053184c0ffdf0239b06850d935/rider-core/src/test/resources/datasets/yml/users.yml#L1-L11).

**Comment by MetallFoX** [comment]
Ah you are right! And I've noticed that xml doesn't preserve order too. I will fix it too if it doesn't require much effort. :)

**Comment by MetallFoX** [comment]
The xls and csv data sets work find but files had different tables order. 
I've changed them. Tests look homogeneous now.

**Comment by rmpestano** [comment]
Awesome, thank you very much!

**Comment by MetallFoX** [comment]
@rmpestano could you publish 1.21.2 ? This blocks me a little.

**Comment by rmpestano** [comment]
Sure, I'll try to publish It tomorrow

**Comment by MetallFoX** [comment]
Thank you!

**Pull request merged**
