### PR TITLE
Add ClasspathFileReplacer

### PR DESCRIPTION
**Pull request by GithubMood**
related ticket: [link](https://github.com/database-rider/database-rider/issues/244)

### CODE REVIEW

**Comment by rmpestano** [comment]
Hi @GithubMood, that's really awesome!

Can we use `[INCLUDE]` as prefix? 

```
TWEET:
  - ID: "1"
    CONTENT: "[INCLUDE]datasets/xml/doc.xml"
``` 

WDYT?

Thank you!

**Comment by GithubMood** [comment]
@rmpestano Sure, make sense.

What about the class name? Should I rename it as well? (For instance: IncludeFileReplacements or just IncludeReplacements)?

**Comment by rmpestano** [comment]
> What about the class name? Should I rename it as well? (For instance: IncludeFileReplacements or just IncludeReplacements)?

I'd go for `IncludeReplacements` but I'm ok with both, your choice ;)

**Comment by GithubMood** [comment]
@rmpestano Done:) 

I would advise to squash commits during merge as there was "small typo fix" commit.

**Pull request merged**
