### PR TITLE
Fixed schema resolving on postgresql

### LINKED ISSUE #63: cleanBefore does not work with multiple schemas on postrgres
Hi, guys!

I thank you for this tool. I use 1.2.5 version in my project and I faced with such a problem:
when using multiple schemas on postgresql 9.4 and higher with full qualified table names and cleanBefore = true, errors occurs and tables are not cleaned. I looked at the sources and found this code `schemaName = result.getString("TABLE_SCHEMA");` in `DataSetExecutorImpl.resolveSchema(ResultSet result)`, but postgresql driver name this column as TABLE_SCHEM, that's why errors occurs, database-rider can not resolve schemas and find tables by their qualified names. May be you can fix it something like this: `getRiderDataSource().getDBType() == POSTGRESQL ? "TABLE_SCHEM" : "TABLE_SCHEMA"` or more attractive way.

Also, when I try to find a workaround for this, I faced with problem, there is no way to pass a custom DataSetExecutor to DBUnitRule, and I even can't extend and override DataSetExecutorImpl.resolveSchema without copying entire class, because most of all methods are private. May be you should give some extension points?

### PR DESCRIPTION
**Pull request by deadmeat333**
Fixed #63

### CODE REVIEW

**Comment by deadmeat333** [comment]
What does this error mean?

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-scm-publish-plugin:1.1:publish-scm (default-cli) on project rider-core: Execution default-cli of goal org.apache.maven.plugins:maven-scm-publish-plugin:1.1:publish-scm failed: Conversion = 'D'

**Comment by rmpestano** [comment]
Hi @deadmeat333, 

this is due to [.travis script](https://github.com/database-rider/database-rider/blob/e6ebbd7ddaa3db8b6f32f960be6844914c312305/.travis.yml#L18), it tries to publish living docs to the site on every commit, but this will only work on master branch where the variables used in the script are set.

About your PR I didnt have time to test it, but I thank you in advance.

**Comment by deadmeat333** [comment]
Ok, I also tested and found a bug when there are several schemas, the first one is taken and assigned to the  shemaName variable, so for all subsequent tables the first schema will be taken, which is incorrect. I fixed it in new commit.

**Comment by rmpestano** [comment]
Hi @deadmeat333,

I've added an example of test using [postgresql here](https://github.com/database-rider/database-rider/blob/master/rider-core/src/test/java/com/github/database/rider/core/PostgreSQLDatabaseIt.java) (you need docker installed on your machine to run the test), can you add a test case for this PR?

After that I think we can merge into master and release a new version.

Thank you very much!

**Comment by rmpestano** [comment]
Closed by 36cb4f42ce288c1cd9be834d214c8929efc5a618

thank you very much @deadmeat333.

**Pull request closed without merging**
