### PR TITLE
Disable foreign key constraint violation when cleaning database

### PR DESCRIPTION
**Pull request by iakunin**
This pull-request is for issue https://github.com/database-rider/database-rider/issues/202.

* Decorating the [com.github.database.rider.core.dataset.DataSetExecutorImpl#clearDatabase](https://github.com/database-rider/database-rider/blob/master/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L603) method with [disableConstraints()](https://github.com/database-rider/database-rider/blob/b03cf80002ab82e7f918aa56aa8852896f3bac77/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L326) call before and with [enableConstraints()](https://github.com/database-rider/database-rider/blob/master/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L389) call after.

### CODE REVIEW

**Comment by rmpestano** [comment]
Thank you very much @iakunin!

**Comment by iakunin** [comment]
@rmpestano thank you for such a rapid feedback! It was pleasure to me help to improve your project a little bit!

**Comment by iakunin** [comment]
@rmpestano by the way, should I close the original issue by myself? Or you will close it when the code will be released?

**Comment by iakunin** [comment]
@rmpestano I've already seen [your comment](https://github.com/database-rider/database-rider/issues/202#issuecomment-615367701). Many thanks again!

**Pull request merged**
