### PR TITLE
Handle BigInteger on resolving column data type

### PR DESCRIPTION
**Pull request by raderio**
Related to the issue https://github.com/database-rider/database-rider/issues/153

### CODE REVIEW

**Comment by rmpestano** [comment]
Hi @raderio, thank you very much!

Could you add a test for that? We have a [postgre test here](https://github.com/database-rider/database-rider/blob/master/rider-core/src/test/java/com/github/database/rider/core/PostgreSQLDatabaseIt.java) which you could use as reference to make sure your PR fixes #153

**Comment by raderio** [comment]
First should be fixed https://github.com/database-rider/database-rider/issues/152
Because in tests table is in lower case and I get the error 
`NoSuchTableException: The table 'USER' does not exist in schema 'null'`

**Comment by raderio** [comment]
BTW, all conditions are wrong, because `BigInteger` extends `Number` the last conditions is always true for numbers, so it should be if else.
@rmpestano what do you think?

**Comment by raderio** [comment]
However, even if we fix those conditions, this method is not good, because in yaml file for id column I can specify just "1", but in DataSetProvider it should be `BigInteger.valueOf(1)`.
IMHO, the type should be deducted from database.

**Comment by rmpestano** [comment]
> IMHO, the type should be deducted from database, and for YAML file I think it is deducted from database.

Yea, that would be the best way

>  in yaml file for id column I can specify just "1"

In YAML dataset the columnType is set to `DataType.UNKNOWN` ([see here](https://github.com/database-rider/database-rider/blob/59364bffab0b5788832fe68b074b9d7e7cd2a94c/rider-core/src/main/java/com/github/database/rider/core/api/dataset/YamlDataSet.java#L60)) maybe that tells dbunit to infer the type from the database, can you try that?

**Comment by raderio** [comment]
>In YAML dataset the columnType is set to DataType.UNKNOWN (see here) maybe that tells dbunit to infer the type from the database, can you try that?

It works, yay :)

**Comment by raderio** [comment]
In this case, maybe this method is not needed at all.

**Comment by rmpestano** [comment]
> In this case, maybe this method is not needed at all.

Yes, If all tests are green, please remove it!

**Comment by raderio** [comment]
I can not get all tests green even if run them from master., without my changes.

**Comment by rmpestano** [comment]
You're right, the build is failing also on Travis, let me take a look. Thanks

**Comment by rmpestano** [comment]
Now it should be ok, just merge your branch with master. If you need help with that, the following commands should be enough (be sure to commit your local changes before merging):

```
git remote add upstream https://github.com/database-rider/database-rider.git

git fetch upstream

git checkout master

git merge upstream/master


```

**Comment by raderio** [comment]
It is more tricky, because `columnType` is used for example in yaml generation.
So, we can not use `UNKNOWN`, we need to deduct column type from database.

**Comment by rmpestano** [comment]
Hi again @raderio,

I've tested your branch and the only failing tests are DataSetProviderTest. This is expected because these tests do not have a database involved, they generate the dataset in memory, write to a file and then compare/assert the result. This way 

If you look to DataSetProviderIt, which has a database involved, the tests are all passing.


So I'll close your PR and adjust the failing tests, and then release a new version, OK?

Thank you very much for the discussion on #153 which lead to the column type solution.

**Comment by raderio** [comment]
Yes, it is ok, thank you.

**Pull request closed without merging**
